name: Provision Azure and Configure with Ansible

on:
  push:
    branches: [main]

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.0
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: terraform
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
          -backend-config="key=${{ secrets.BACKEND_KEY }}"

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Create Ansible Inventory and Keys
      working-directory: ansible
      run: |
        # Create SSH key file with proper permissions first (security best practice)
        echo "$(terraform -chdir='../terraform' output -raw private_key)" > id_rsa
        chmod 600 id_rsa
        
        # Get the admin username once
        USERNAME=$(terraform -chdir='../terraform' output -raw vm_username || echo "azureuser")
        
        # Create inventory header
        echo "[web]" > inventory.ini
        
        # Get IPs as JSON array and process with proper error handling
        PUBLIC_IPS=$(terraform -chdir='../terraform' output -json public_ip_addresses)
        if [[ $? -ne 0 ]]; then
          echo "Error getting public IP addresses from Terraform output"
          exit 1
        fi
        
        # Handle both array and single string output formats (resilient approach)
        if echo "$PUBLIC_IPS" | jq -e 'type == "array"' >/dev/null; then
          # Process array of IPs
          for IP in $(echo "$PUBLIC_IPS" | jq -r '.[]'); do
            echo "$IP ansible_user=$USERNAME ansible_ssh_private_key_file=id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" >> inventory.ini
          done
        else
          # Handle single IP (not in array)
          IP=$(echo "$PUBLIC_IPS" | jq -r '.')
          echo "$IP ansible_user=$USERNAME ansible_ssh_private_key_file=id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" >> inventory.ini
        fi

        cat inventory.ini | grep -v private_key

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible Playbook
      working-directory: ansible
      run: ansible-playbook -i inventory.ini site.yml
